site_name: Land Change Monitor
site_description: Near real-time disturbance detection using satellite time series
site_url: https://jonasViehweger.github.io/change-detection
repo_url: https://github.com/jonasViehweger/change-detection
repo_name: jonasViehweger/change-detection

theme:
  name: material
  logo: assets/logo_grayscale.svg
  custom_dir: overrides
  palette:
    - scheme: light-change
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: dark-change
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Reference: reference.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
